language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: U6a5w+ELQU3+esQnSV1EkAvPZqVpklbqQyfWQW6bqLMHWiHOnbH0e+Lm70qoc9ncW+EidBDIeLQ817PNI03gO9ABtCILois90aPFpsgbEOFm6oHvuMTzviW2B7Tjf27mDKzCxLPn/ZD2UWjNmic7uR85ohpBEXFfC/EeBcw03Q/NPCsSe6kueXqfKx65NdXBILFaZw0/W1RZgQTcAJTwDrWWc6HuqNCWE3mj1HjNHGKavESCrcgFcc0gVYri3a2PhXRnzoM2pgnYoZ6dVMdTp4/Uik1EWy946l/u4jkmPMk+MKnpHbX65j0D9HQXYJR4MdIFg08EODvcaP+J2CZJOATjeTOWWqFwZPLdub/yQSMEI2Rfl10B4dGEfm4mTz9kR9eZzrAZGd949gESTddsdlcuyzxXtgVSNC2GmbYF3hei8EJbdSn0mGUX8AVXpueDhM6ooKmFHTOFK9n+sothz3NQdNhVIefDueRMbL0Qou8sKzIx9sGTXQyVwakBD9HBSafqQzvo4tztEIjAjndqn8IGHmzDsuEc6JxOr3Sv/MDAAOLqXEYhER5mF5m6Kqg4Ih1UTaaLmLzSKK5amQ924svvtiyRSw3tEIRB5McL4Q0pbJFPkxx7zFjhpQP7wJHlF/nU8Z/zUKU0vd0PsWnE1ep1sbcVHZYc08TEBcGHKM4=
  app: myyntitykki
  on:
    repo: mlampola/myyntitykki
