language: java

jdk:
- oraclejdk8

deploy:
  provider: heroku
  api_key:
    secure: "Lc9mjBidk50z8v0SRe5H9PKK5Rv4qlhPEJ/qhqafm4EAQtbg0Bx2ZcruRegGR4mP/smeuNxNN7B5lfdkT3CTIy9E178kZWb+fWXJ4BtDSwBnRkG6lp34dwBVSpK/byPPQUmEyTCCheg+Gcb7munExDrp5ZXgxACqVAPdwF9xA7sTTaF7i3N8LPfnv8VmBefTWByO71nTJ/CYRz/c0u5jeO8Whp+XcPHNe4MP9Ip+2MOOdXyIdN12k/Dkus0R3Aflx/U1dut7pcHnYuxejM42uBM2l02BDwZIITNW64qHJMV3HAQqzKX9J0tGvt/VVISNowCx8XdUEuZOZY5PltNpJkw4ZsNFq0WdXMYDZ2KekVkjUGoO2lDfvHPkQcJTs5PbpAZnbfsqRPxrcrxSTuRDOS8N1Wg7ufO+oaSP8cU8QLWIjUmxUPsa9GEfBE9oOsRmmLN1VlT6VDPLCOJ88MjQx6+it5LJqc7zoTN0Px5eG1taZYG5b+BX75/LMJrPzls0Nl6XXWKqzU6zfVR0A1UOqjcGaOd84Yl/AjEwjK8XQJhCJ7pDKH+rWmfZcpxESev2XlhTSIrfyE49jRPEp7h2JAJ0o+pHOSHLFy+8IaZ3ZR7qD7rZCS9SM1nMp9vinIFJUELMEkBLGtffadN+pKlpaSVpdT/nSw/yVM6C4j/L0YM="

app: arcane-beach-84135
