language: java
jdk:
- oraclejdk8
sudo: false
script: mvn clean verify
deploy:
  api_key:
    secure: u8E9wahY5TaFXx+gYLFxOTMBSV0VtinJEqQ8y1gU2ZkEyRr18xf2l1eS5CGVMzopg0ABhochU8rRkT/63IodDvbjxzvPyTg6iefjSp8p9qULmsVALPYb3YBt9d+ue3YGNRAOeCRJuLkMeKHZJpLnbR6L3V8yXNDTPJjsl9CT+WJOpal16/qMo99q6VAOg+0J52dyomHXffC4UDv00Xv5f0f8giF8v4Jch3xktYFS9g6HwCdCjiTSu6X9ZxQ+BaLx0Sx7fpOXIkSSYC50nxu+gNMqzcmsXBiEBr8tBPXHZELOveyGySjVxKLzcYLmbGHECqGLh31V8NmzlQnNH9X4/HMrh+6eVWmMuMpeNXyou1xo3wB+F4nyhEHZ8O2Aj/uk42SBHibhOnSTO2nazzRR3Qk9kqP+EyuYU5x2F+Y4RLos6XTgPn7EgdhK6Nu0Z5QirZGgHV06o4JqmV5qWbA78sHWm5aPlKJUhtHAGsNx/BDZSn2oa+WZe9NpLTVY0nTpA91tqyvSNB7FPKxxuB4kIYnBFISoBm084Osg7JyR3bkOHnlH20MkwUtsabh5RYlRvWcEX3YRF/kHt+Js4Rb7aJXe5499EdloAj4tgmhUZ08+s+0OBU/zDmhs1UMYqhnxXQw2qpRHB/lkICYemWzpuXnKZxlKhET29lsRyn9v7p0=
