language: java

jdk:
- oraclejdk8

deploy:
  provider: heroku
  api_key:
    secure: BhtzWoHYI5V7GQ6mM355j0R+BHQ2/PhrTjR4IPqwgtPCqVCm45dAZ1ivJLXLPUBR8dnD9VSTXW/rkQPGghWt++3N0iAyIRcbE+6ME7W+NMngqILl6HOLVWfxI8+0GQp0WG5/6ryC1452bq/Frsk3YARL7MKS2gL4JsjvZudIJKVLXsrvi0S0tWkvVxA7zUBrRRvxg6pGayK3yykraWcq38fTgvfsBtFe9OWiMGF+gVPlWFttO21BN3DvSc9NBarKhsyCsvjMj2vT9ylTLA08oSX6ulytdcIWa2FCFHxo7sT+1lgJ3VKO16lkpALip0WGr990KSLNK7oAiKZGzjcCVC3+QoS9Va90ti+vPvlBlnkmlXF6OR1srB+Vzdm4NFH6Fzior93qQwIq8RxdzxtSbxxlTbxWfFp1mLEt8oRgF2xQkMX8xgRc0CDtP77K/o8JIktO2BqTVcqoH/FgkmxAAs4XcA/UJJzM9ghix4mPTtn0nSsuIOvyNu7CPiPEIGltc4YnCGhVHESSPTMxjzDFSedowsUSHHu4pw9DsC/NwHQk7yU/b9eZ5n1aC+PJYdJqLDYLeeQnk4g2nskE8f44gojZind5VknlPfzzrtKYLsj6zbE6j+dZaiXtq5YCgqlG/+dGMgovyVAkrnsWsTi8lic5law4kbG7LcxSDbNYvR4=
